// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/helpers"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type ExternalAccessIntegrationAssert struct {
	*assert.SnowflakeObjectAssert[sdk.ExternalAccessIntegration, sdk.AccountObjectIdentifier]
}

func ExternalAccessIntegration(t *testing.T, id sdk.AccountObjectIdentifier) *ExternalAccessIntegrationAssert {
	t.Helper()
	return &ExternalAccessIntegrationAssert{
		assert.NewSnowflakeObjectAssertWithTestClientObjectProvider(sdk.ObjectType("ExternalAccessIntegration"), id, func(testClient *helpers.TestClient) assert.ObjectProvider[sdk.ExternalAccessIntegration, sdk.AccountObjectIdentifier] {
			return testClient.ExternalAccessIntegration.Show
		}),
	}
}

func ExternalAccessIntegrationFromObject(t *testing.T, externalAccessIntegration *sdk.ExternalAccessIntegration) *ExternalAccessIntegrationAssert {
	t.Helper()
	return &ExternalAccessIntegrationAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectTypeExternalAccessIntegration, externalAccessIntegration.ID(), externalAccessIntegration),
	}
}

func (e *ExternalAccessIntegrationAssert) HasName(expected string) *ExternalAccessIntegrationAssert {
	e.AddAssertion(func(t *testing.T, o *sdk.ExternalAccessIntegration) error {
		t.Helper()
		if o.Name != expected {
			return fmt.Errorf("expected name: %v; got: %v", expected, o.Name)
		}
		return nil
	})
	return e
}

func (e *ExternalAccessIntegrationAssert) HasExternalAccessType(expected string) *ExternalAccessIntegrationAssert {
	e.AddAssertion(func(t *testing.T, o *sdk.ExternalAccessIntegration) error {
		t.Helper()
		if o.ExternalAccessType != expected {
			return fmt.Errorf("expected external access type: %v; got: %v", expected, o.ExternalAccessType)
		}
		return nil
	})
	return e
}

func (e *ExternalAccessIntegrationAssert) HasCategory(expected string) *ExternalAccessIntegrationAssert {
	e.AddAssertion(func(t *testing.T, o *sdk.ExternalAccessIntegration) error {
		t.Helper()
		if o.Category != expected {
			return fmt.Errorf("expected category: %v; got: %v", expected, o.Category)
		}
		return nil
	})
	return e
}

func (e *ExternalAccessIntegrationAssert) HasEnabled(expected bool) *ExternalAccessIntegrationAssert {
	e.AddAssertion(func(t *testing.T, o *sdk.ExternalAccessIntegration) error {
		t.Helper()
		if o.Enabled != expected {
			return fmt.Errorf("expected enabled: %v; got: %v", expected, o.Enabled)
		}
		return nil
	})
	return e
}

func (e *ExternalAccessIntegrationAssert) HasComment(expected string) *ExternalAccessIntegrationAssert {
	e.AddAssertion(func(t *testing.T, o *sdk.ExternalAccessIntegration) error {
		t.Helper()
		if o.Comment != expected {
			return fmt.Errorf("expected comment: %v; got: %v", expected, o.Comment)
		}
		return nil
	})
	return e
}

func (e *ExternalAccessIntegrationAssert) HasCreatedOn(expected time.Time) *ExternalAccessIntegrationAssert {
	e.AddAssertion(func(t *testing.T, o *sdk.ExternalAccessIntegration) error {
		t.Helper()
		if o.CreatedOn != expected {
			return fmt.Errorf("expected created on: %v; got: %v", expected, o.CreatedOn)
		}
		return nil
	})
	return e
}
