// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ShowExternalAccessIntegrationSchema represents output of SHOW query for the single ExternalAccessIntegration.
var ShowExternalAccessIntegrationSchema = map[string]*schema.Schema{
	"name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"external_access_type": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"category": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"enabled": {
		Type:     schema.TypeBool,
		Computed: true,
	},
	"comment": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"created_on": {
		Type:     schema.TypeString,
		Computed: true,
	},
}

var _ = ShowExternalAccessIntegrationSchema

func ExternalAccessIntegrationToSchema(externalAccessIntegration *sdk.ExternalAccessIntegration) map[string]any {
	externalAccessIntegrationSchema := make(map[string]any)
	externalAccessIntegrationSchema["name"] = externalAccessIntegration.Name
	externalAccessIntegrationSchema["external_access_type"] = externalAccessIntegration.ExternalAccessType
	externalAccessIntegrationSchema["category"] = externalAccessIntegration.Category
	externalAccessIntegrationSchema["enabled"] = externalAccessIntegration.Enabled
	externalAccessIntegrationSchema["comment"] = externalAccessIntegration.Comment
	externalAccessIntegrationSchema["created_on"] = externalAccessIntegration.CreatedOn.String()
	return externalAccessIntegrationSchema
}

var _ = ExternalAccessIntegrationToSchema
