// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ validatable = new(CreateExternalAccessIntegrationOptions)
	_ validatable = new(AlterExternalAccessIntegrationOptions)
	_ validatable = new(DropExternalAccessIntegrationOptions)
	_ validatable = new(ShowExternalAccessIntegrationOptions)
	_ validatable = new(DescribeExternalAccessIntegrationOptions)
)

func (opts *CreateExternalAccessIntegrationOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	if valueSet(opts.AllowedApiAuthenticationIntegrations) {
		if !exactlyOneValueSet(opts.AllowedApiAuthenticationIntegrations.NoIntegrations, opts.AllowedApiAuthenticationIntegrations.AllowedList) {
			errs = append(errs, errExactlyOneOf("CreateExternalAccessIntegrationOptions.AllowedApiAuthenticationIntegrations", "NoIntegrations", "AllowedList"))
		}
	}
	if valueSet(opts.AllowedAuthenticationSecrets) {
		if !exactlyOneValueSet(opts.AllowedAuthenticationSecrets.AllSecrets, opts.AllowedAuthenticationSecrets.NoSecrets, opts.AllowedAuthenticationSecrets.AllowedList) {
			errs = append(errs, errExactlyOneOf("CreateExternalAccessIntegrationOptions.AllowedAuthenticationSecrets", "AllSecrets", "NoSecrets", "AllowedList"))
		}
	}
	return JoinErrors(errs...)
}

func (opts *AlterExternalAccessIntegrationOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	if !exactlyOneValueSet(opts.Set, opts.Unset, opts.SetTags, opts.UnsetTags) {
		errs = append(errs, errExactlyOneOf("AlterExternalAccessIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"))
	}
	if valueSet(opts.Set) {
		if !anyValueSet(opts.Set.AllowedNetworkRules, opts.Set.AllowedApiAuthenticationIntegrations, opts.Set.AllowedAuthenticationSecrets, opts.Set.Enabled, opts.Set.Comment) {
			errs = append(errs, errAtLeastOneOf("AlterExternalAccessIntegrationOptions.Set", "AllowedNetworkRules", "AllowedApiAuthenticationIntegrations", "AllowedAuthenticationSecrets", "Enabled", "Comment"))
		}
		if valueSet(opts.Set.AllowedApiAuthenticationIntegrations) {
			if !exactlyOneValueSet(opts.Set.AllowedApiAuthenticationIntegrations.NoIntegrations, opts.Set.AllowedApiAuthenticationIntegrations.AllowedList) {
				errs = append(errs, errExactlyOneOf("AlterExternalAccessIntegrationOptions.Set.AllowedApiAuthenticationIntegrations", "NoIntegrations", "AllowedList"))
			}
		}
		if valueSet(opts.Set.AllowedAuthenticationSecrets) {
			if !exactlyOneValueSet(opts.Set.AllowedAuthenticationSecrets.AllSecrets, opts.Set.AllowedAuthenticationSecrets.NoSecrets, opts.Set.AllowedAuthenticationSecrets.AllowedList) {
				errs = append(errs, errExactlyOneOf("AlterExternalAccessIntegrationOptions.Set.AllowedAuthenticationSecrets", "AllSecrets", "NoSecrets", "AllowedList"))
			}
		}
	}
	if valueSet(opts.Unset) {
		if !anyValueSet(opts.Unset.AllowedNetworkRules, opts.Unset.AllowedApiAuthenticationIntegrations, opts.Unset.AllowedAuthenticationSecrets, opts.Unset.Comment) {
			errs = append(errs, errAtLeastOneOf("AlterExternalAccessIntegrationOptions.Unset", "AllowedNetworkRules", "AllowedApiAuthenticationIntegrations", "AllowedAuthenticationSecrets", "Comment"))
		}
	}
	return JoinErrors(errs...)
}

func (opts *DropExternalAccessIntegrationOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	return JoinErrors(errs...)
}

func (opts *ShowExternalAccessIntegrationOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	return JoinErrors(errs...)
}

func (opts *DescribeExternalAccessIntegrationOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	return JoinErrors(errs...)
}
